### PR TITLE
Simple  App Backend using GO in docker

### LINKED ISSUE #10: Simple backend app in docker
Create a CRUD app using any backend technology you prefer (database optional)

Deploy it as a dockerised container. Add your docker file.

Please suggest the language you are undertaking as a comment below.

Add them into a single directory with your language

Example ->  docker_crud_app/python , docker_crud_app/nodejs

### PR DESCRIPTION
**Pull request by Pushkarm029**
Fixes #10

### CODE REVIEW

**Comment by DiptoChakrabarty** [comment]
Hey @Pushkarm029 thanks for the PR but you might have gotten a bit confused

It seems this is an already built app you have, what we want in the issue is a simple golang app with 4 endpoints for GET, POST , DELETE , UPDATE.
The main aim is to run a golang api from docker and ideally we want the api to a simple CRUD app not a full scale application

**Comment by DiptoChakrabarty** [comment]
you might want to look at PR #15 for an example

**Comment by DiptoChakrabarty** [comment]
please tell if you want to make a new PR or edit this one

**Comment by Pushkarm029** [comment]
@DiptoChakrabarty srry, i will edit this one

**Comment by Pushkarm029** [comment]
@DiptoChakrabarty please review

**Review by DiptoChakrabarty — APPROVED** [review]

**Pull request merged**
